INSERT INTO exercises (name, muscle_group, emoji, is_system) VALUES
  ('Arnold Press Haltères',        'Épaules',             '🏋️', true),
  ('Papillon bras tendus',         'Pectoraux',           '🦅', true),
  ('Élévations latérales',         'Épaules',             '🙆', true),
  ('Skull Crusher incliné',        'Triceps',             '💀', true),
  ('Presse à cuisse',              'Quadriceps',          '🦵', true),
  ('Élévation mollet machine',     'Mollets',             '🦶', true),
  ('Crunch assis machine',         'Abdos',               '🔥', true),
  ('Rangées prise serrée neutre',  'Dos',                 '🚣', true),
  ('Rangées prise large pronation','Dos',                 '💪', true),
  ('Curls biceps inclinés',        'Biceps',              '💪', true),
  ('Papillon inverse',             'Deltoïdes post.',     '🦅', true),
  ('Shrugs haltères',              'Trapèzes',            '🤷', true),
  ('Soulevé de terre roumain',     'Ischios / Bas du dos','🏋️', true),
  ('Extension du dos machine',     'Lombaires',           '🔙', true),
  ('Crunch à genoux poulie',       'Abdos',               '🔥', true),
  ('Développé couché',             'Pectoraux',           '🏋️', true),
  ('Tirage latéral prise large',   'Dos',                 '🚣', true),
  ('Pec Deck bras tendus',         'Pectoraux',           '🦅', true),
  ('Extension triceps corde',      'Triceps',             '💪', true),
  ('Curls stricts barre',          'Biceps',              '🦾', true),
  ('Extension de jambe machine',   'Quadriceps',          '🦵', true),
  ('Leg Curl assis',               'Ischios',             '🦵', true),
  ('Extension mollet machine',     'Mollets',             '🦶', true);
