/// <reference types="node" />
import { readFileSync } from "node:fs"

import { describe, expect, it } from "vitest"

/**
 * The named GymLogic **skin** contract (ADR 0027, T303): a DTCG *semantic overlay*
 * (`glSkin.json`, no `primitive`) that the app CSS is derived from via
 * `renderCss(resolveSkin(default, glSkin))` — a committed artifact guarded by
 * `glSkin:check`. This test pins the source-level invariants: the skin owns semantic
 * slots only, the build script uses the public Nomos surface, and the app imports the
 * derived artifact instead of the heart default.
 */
const sources = import.meta.glob(
  ["../styles/glSkin.json", "../../scripts/build-gl-skin.mjs", "../../package.json"],
  { query: "?raw", eager: true, import: "default" },
) as Record<string, string>

const skinJson = sources["../styles/glSkin.json"]
const buildScript = sources["../../scripts/build-gl-skin.mjs"]
const packageJson = sources["../../package.json"]

// CSS is not readable through `?raw` under Vitest (CSS transforms win), so the two
// stylesheets are read from disk relative to the repo root (Vitest's cwd).
const generatedCss = readFileSync("src/styles/glSkin.generated.css", "utf8")
const globalsCss = readFileSync("src/styles/globals.css", "utf8")

describe("glSkin — named GymLogic skin", () => {
  it("carries semantic slots only, never a `primitive`", () => {
    const skin = JSON.parse(skinJson) as { primitive?: unknown; semantic?: Record<string, unknown> }
    expect(skin.primitive).toBeUndefined()
    expect(skin.semantic?.color).toBeTypeOf("object")
    expect(skin.semantic?.radius).toBeTypeOf("object")
    expect(skin.semantic?.type).toBeTypeOf("object")
  })

  it("is built from the public Nomos surface and handles --check", () => {
    expect(buildScript).toMatch(/from ['"]@nomosui\/react['"]/)
    expect(buildScript).toMatch(/resolveSkin/)
    expect(buildScript).toMatch(/renderCss/)
    expect(buildScript).toMatch(/--check/)
  })

  it("derives an artifact that carries the GL teal", () => {
    expect(generatedCss).toMatch(/--nomos-color-primary: 174 100% 39%/)
    expect(generatedCss).toMatch(/Generated by scripts\/build-gl-skin\.mjs/)
  })

  it("the app imports the derived artifact, not the heart default", () => {
    expect(globalsCss).toMatch(/@import ['"]\.\/glSkin\.generated\.css['"]/)
    expect(globalsCss).not.toMatch(/@nomosui\/react\/tokens\/tokens\.generated\.css/)
  })

  it("guards the artifact against drift (glSkin:check)", () => {
    expect(packageJson).toMatch(/"glSkin":\s*"node scripts\/build-gl-skin\.mjs"/)
    expect(packageJson).toMatch(/"glSkin:check":\s*"node scripts\/build-gl-skin\.mjs --check"/)
  })
})
