/// <reference types="node" />
import { readFileSync } from "node:fs"

import { describe, expect, it } from "vitest"

/**
 * The named GymLogic **skin** contract (ADR 0027, T303): a DTCG *semantic overlay*
 * (`glSkin.json`, no `primitive`) that the app CSS is derived from via
 * `renderCss(resolveSkin(default, glSkin))` — a committed artifact guarded by
 * `glSkin:check`. This test pins the source-level invariants: the skin owns semantic
 * slots only, the build script uses the public Nomos surface, and the app imports the
 * derived artifact instead of the heart default.
 */
const sources = import.meta.glob(
  [
    "../styles/glSkin.json",
    "../../scripts/build-gl-skin.mjs",
    "../../scripts/build-mcp-view.mjs",
    "../../package.json",
  ],
  { query: "?raw", eager: true, import: "default" },
) as Record<string, string>

const skinJson = sources["../styles/glSkin.json"]
const buildScript = sources["../../scripts/build-gl-skin.mjs"]
const viewBuildScript = sources["../../scripts/build-mcp-view.mjs"]
const packageJson = sources["../../package.json"]

// CSS is not readable through `?raw` under Vitest (CSS transforms win), so the two
// stylesheets are read from disk relative to the repo root (Vitest's cwd). The CI
// workflow is read the same way (dotfile path, not glob-able through `?raw`).
const generatedCss = readFileSync("src/styles/glSkin.generated.css", "utf8")
const globalsCss = readFileSync("src/styles/globals.css", "utf8")
const ciYml = readFileSync(".github/workflows/ci.yml", "utf8")

// Every `src/**` source file, to prove no component reads a legacy HSL variable
// directly (T305). TS/TSX come through `?raw`; CSS is read from disk (see above),
// `globals.css` excluded since it is the legacy `@theme` definition itself.
const sourceFiles = import.meta.glob("../**/*.{ts,tsx}", {
  query: "?raw",
  eager: true,
  import: "default",
}) as Record<string, string>
const cssFiles = Object.fromEntries(
  Object.keys(import.meta.glob("../**/*.css"))
    .filter((path) => !path.endsWith("/globals.css"))
    .map((path) => [path, readFileSync(path.replace(/^\.\.\//, "src/"), "utf8")]),
)
const allSourceFiles = { ...sourceFiles, ...cssFiles }

describe("glSkin — named GymLogic skin", () => {
  it("carries semantic slots only, never a `primitive`", () => {
    const skin = JSON.parse(skinJson) as { primitive?: unknown; semantic?: Record<string, unknown> }
    expect(skin.primitive).toBeUndefined()
    expect(skin.semantic?.color).toBeTypeOf("object")
    expect(skin.semantic?.radius).toBeTypeOf("object")
    expect(skin.semantic?.type).toBeTypeOf("object")
  })

  it("is built from the public Nomos surface and handles --check", () => {
    expect(buildScript).toMatch(/from ['"]@nomosui\/react['"]/)
    expect(buildScript).toMatch(/resolveSkin/)
    expect(buildScript).toMatch(/renderCss/)
    expect(buildScript).toMatch(/--check/)
  })

  it("derives an artifact that carries the GL teal", () => {
    expect(generatedCss).toMatch(/--nomos-color-primary: 174 100% 39%/)
    expect(generatedCss).toMatch(/Generated by scripts\/build-gl-skin\.mjs/)
  })

  it("the app imports the derived artifact, not the heart default", () => {
    expect(globalsCss).toMatch(/@import ['"]\.\/glSkin\.generated\.css['"]/)
    expect(globalsCss).not.toMatch(/@nomosui\/react\/tokens\/tokens\.generated\.css/)
  })

  it("guards the artifact against drift (glSkin:check)", () => {
    expect(packageJson).toMatch(/"glSkin":\s*"node scripts\/build-gl-skin\.mjs"/)
    expect(packageJson).toMatch(/"glSkin:check":\s*"node scripts\/build-gl-skin\.mjs --check"/)
  })

  it("the view build inlines the same derived artifact, not the heart default", () => {
    // The parity claim (ADR 0027 §6): the app CSS and the view CSS are the *same*
    // resolved skin. Repointing this read to `tokens.generated.css` must fail here.
    expect(viewBuildScript).toMatch(/src\/styles\/glSkin\.generated\.css/)
    expect(viewBuildScript).not.toMatch(/tokens\.generated\.css/)
  })

  it("neither build script sources tokens from the heart default", () => {
    expect(buildScript).not.toMatch(/tokens\.generated\.css/)
    expect(viewBuildScript).not.toMatch(/tokens\.generated\.css/)
  })

  it("CI runs glSkin:check before view:check", () => {
    const glIndex = ciYml.indexOf("npm run glSkin:check")
    const viewIndex = ciYml.indexOf("npm run view:check")
    expect(glIndex).toBeGreaterThan(-1)
    expect(viewIndex).toBeGreaterThan(-1)
    expect(glIndex).toBeLessThan(viewIndex)
  })

  it("no source file reads a legacy HSL variable directly", () => {
    const legacyVar = /var\(--(primary|muted|border|input|ring|card|background|foreground)\b/
    const offenders = Object.entries(allSourceFiles)
      .filter(([, content]) => legacyVar.test(content))
      .map(([path]) => path)
    expect(offenders).toEqual([])
  })

  it("globals.css defines no legacy `--color-*` slot (T306)", () => {
    // The colour mapping now lives in `@nomosui/react/tokens/theme.css`; the GL
    // `@theme` block keeps only `--animate-*`. A stray semantic slot here would
    // shadow the skin. `--color-gray-200` (Tailwind's own) is not a legacy slot.
    const legacyColorSlot =
      /--color-(border|input|ring|background|foreground|primary|secondary|destructive|muted|accent|popover|card|teal)\b/
    expect(globalsCss).not.toMatch(legacyColorSlot)
  })

  it("globals.css reads no legacy HSL variable (T306)", () => {
    // Reads go through `--nomos-color-*`, or the GL-owned `--heatmap-*` ramp.
    // `--animate-*` is not a colour; `--nomos-color-*` must not be caught.
    const legacyVar = /var\(--(primary|muted|border|input|ring|card|background|foreground)\b/
    expect(globalsCss).not.toMatch(legacyVar)
  })
})
