#!/usr/bin/env node
/**
 * Dérive le CSS de l'app depuis le skin GL nommé (`src/styles/glSkin.json`), un overlay
 * sémantique posé sur le défaut de `@nomosui/react` (ADR 0027, T303). Écrit l'artefact
 * committé `src/styles/glSkin.generated.css`. Rejouer : `npm run glSkin` ; vérifier la
 * dérive : `npm run glSkin:check`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { renderCss, resolveSkin } from '@nomosui/react'

const require = createRequire(import.meta.url)
const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..')
const TARGET = path.join(ROOT, 'src/styles/glSkin.generated.css')

const header = `/*
 * Generated by scripts/build-gl-skin.mjs — do not edit by hand.
 * Replay: npm run glSkin
 */`

const check = process.argv.includes('--check')

const defaultTokens = JSON.parse(
  readFileSync(require.resolve('@nomosui/react/tokens/tokens.json'), 'utf8'),
)
const skin = JSON.parse(readFileSync(path.join(ROOT, 'src/styles/glSkin.json'), 'utf8'))

const css = renderCss(resolveSkin(defaultTokens, skin)).replace(/^\/\*[\s\S]*?\*\//, header)

if (check) {
  let current = ''
  try {
    current = readFileSync(TARGET, 'utf8')
  } catch {
    current = ''
  }
  if (current !== css) {
    console.error('src/styles/glSkin.generated.css is stale: replay `npm run glSkin`.')
    process.exit(1)
  }
  console.log('glSkin artifact is up to date.')
} else {
  writeFileSync(TARGET, css)
  console.log('wrote src/styles/glSkin.generated.css')
}
