tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a292e",
        "surface-container": "#1f1f23",
        "outline-variant": "#3c4a45",
        "secondary-container": "#494851",
        background: "#131317",
        "on-secondary": "#303038",
        "on-primary": "#00382d",
        "on-surface": "#e4e1e7",
        "on-primary-container": "#004e40",
        "on-surface-variant": "#bacac3",
        "surface-dim": "#131317",
        outline: "#85948e",
        "surface-container-lowest": "#0e0e12",
        "primary-container": "#00c9a7",
        "on-background": "#e4e1e7",
        "surface-bright": "#39393d",
        "on-secondary-container": "#b9b7c2",
        error: "#ffb4ab",
        "surface-variant": "#353439",
        secondary: "#c7c5d0",
        "surface-container-highest": "#353439",
        muted: "#999999",
        "on-error": "#690005",
        "surface-tint": "#38debb",
        surface: "#15151c",
        "on-primary-fixed-variant": "#005142",
        foreground: "#f2f2f2",
        "inverse-primary": "#006b58",
        "inverse-on-surface": "#303034",
        border: "#2d2d37",
        primary: "#44e5c2",
        "surface-container-low": "#1b1b1f",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap-mobile": "4rem",
        "container-prose": "48rem",
        "unit-lg": "24px",
        "unit-sm": "8px",
        "unit-xs": "4px",
        "unit-xl": "32px",
        gutter: "1rem",
        "unit-md": "16px",
      },
      fontFamily: {
        "body-lg": ["Geist"],
        "body-sm": ["Geist"],
        label: ["Geist"],
        "headline-sm": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "headline-lg": ["Geist"],
        mono: ["Geist Mono"],
      },
      fontSize: {
        "body-lg": ["1.125rem", { lineHeight: "1.65", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.55", fontWeight: "400" }],
        label: ["0.875rem", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["1.875rem", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.65", fontWeight: "400" }],
        "headline-sm": ["1.125rem", { lineHeight: "1.35", letterSpacing: "-0.01em", fontWeight: "600" }],
        mono: ["0.875rem", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
}
